'use client';
import {useEffect,useRef,useState} from 'react';
import type {Chart} from '@/lib/analysis';
import {DataChart} from './data-chart';
import {placeTiles,composeDashboard,type Tile,type KpiPlacement} from '@/lib/canvas-layout';
import {useLanguage} from '@/lib/language';
export function DashboardCanvas({charts,dataset,onCategory,filterColumn,kpis={},filters,layout,kpiPlacement}:{charts:Chart[];dataset:string;onCategory?:(column:string,value:string)=>void;filterColumn?:string;kpis?:Record<string,number>;filters?:React.ReactNode;layout?:string;kpiPlacement?:KpiPlacement}){
 const {locale}=useLanguage(),id=locale==='id';const [saved,setSaved]=useState<Tile[]>([]),[edit,setEdit]=useState(false),[placement,setPlacement]=useState<KpiPlacement|undefined>();const root=useRef<HTMLDivElement>(null);
 const keys=charts.map((c,i)=>c.id||`${c.title}:${i}`);
 const compositionKey=keys.join('|');
 useEffect(()=>{setSaved([])},[compositionKey]);
 const [width,setWidth]=useState(1200),[minimums,setMinimums]=useState<Record<string,number>>({});
 useEffect(()=>{const el=root.current;if(!el)return;const observer=new ResizeObserver(entries=>setWidth(Math.round(entries[0].contentRect.width)));observer.observe(el);return()=>observer.disconnect()},[]);
 const automatic=composeDashboard(charts,keys,Object.keys(kpis),{width:1600,layout,kpiPlacement:placement||kpiPlacement,minimums,editing:edit});
 const activeKeys=new Set(automatic.map(t=>t.key));
 const overrides=saved.filter(t=>activeKeys.has(t.key));
 const tiles=placeTiles([...overrides,...automatic.filter(t=>!overrides.some(s=>s.key===t.key))].map(t=>({...t,h:Math.max(t.h,minimums[t.key]||0)})));
 function minimumHeight(key:string,h:number){setMinimums(previous=>previous[key]===h?previous:{...previous,[key]:h})}
 const canvasRows=Math.max(1,...tiles.map(t=>t.y+t.h));
 const logicalHeight=Math.max(900,canvasRows*100+24),logicalWidth=logicalHeight*16/9,scale=width/logicalWidth;
 function update(tile:Tile){setSaved(placeTiles([tile,...tiles.filter(t=>t.key!==tile.key)]))}
 function gesture(e:React.PointerEvent<HTMLButtonElement>,tile:Tile,resize=false){e.preventDefault();const el=e.currentTarget;el.setPointerCapture(e.pointerId);const startX=e.clientX,startY=e.clientY,rect=root.current!.getBoundingClientRect();let next=tile;const move=(event:PointerEvent)=>{const dx=Math.round((event.clientX-startX)/rect.width*12),dy=Math.round((event.clientY-startY)/rect.height*canvasRows);next={...tile,...(resize?{w:Math.max(3,Math.min(12-tile.x,tile.w+dx)),h:Math.max(1,Math.max(1,tile.h+dy))}:{x:Math.max(0,Math.min(12-tile.w,tile.x+dx)),y:Math.max(0,tile.y+dy)})};update(next)};const stop=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',stop);el.removeEventListener('pointercancel',stop)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',stop);el.addEventListener('pointercancel',stop)}
 return <section className="canvas-workspace"><div className="canvas-toolbar"><div><strong>Dashboard</strong></div>{edit&&<><select aria-label={id?'Susunan KPI':'KPI layout'} value={placement||kpiPlacement||'auto'} onChange={e=>{setPlacement(e.target.value as KpiPlacement);setSaved([])}}><option value="auto">{id?'Otomatis':'Automatic'}</option><option value="horizontal">{id?'Mendatar':'Horizontal'}</option><option value="sidebar">{id?'Di samping':'Sidebar'}</option><option value="grouped">{id?'Berkelompok':'Grouped'}</option></select><button onClick={()=>setSaved([])}>{id?'Susun otomatis':'Auto arrange'}</button></>}<button onClick={()=>setEdit(v=>!v)} aria-pressed={edit}>{edit?(id?'Selesai menyusun':'Done arranging'):(id?'Atur tata letak':'Arrange layout')}</button></div>{filters&&<div className="canvas-filters">{filters}</div>}<div ref={root} className="dashboard-frame"><div data-dashboard-canvas className={'dashboard-canvas '+(edit?'editing':'')} style={{width:logicalWidth,height:logicalHeight,transform:`scale(${scale})`,gridTemplateRows:`repeat(${canvasRows}, minmax(0,1fr))`}}>
 {Object.entries(kpis).map(([label,value])=>{const tile=tiles.find(t=>t.key===`kpi:${label}`)!;return <section data-tile-key={`kpi:${label}`} className="canvas-tile canvas-metric metric" key={`kpi:${label}`} style={{gridColumn:`${tile.x+1} / span ${tile.w}`,gridRow:`${tile.y+1} / span ${tile.h}`,display:'flex'}}>{edit&&<div className="tile-tools"><button aria-label={`Move KPI ${label}`} onPointerDown={e=>gesture(e,tile)}>⠿ {id?'Geser':'Move'}</button><select aria-label={`Width KPI ${label}`} value={tile.w} onChange={e=>update({...tile,w:Number(e.target.value)})}>{[2,3,4,6,12].map(w=><option key={w} value={w}>{Math.round(w/12*100)}%</option>)}</select></div>}<span>{label}</span><strong>{new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(value)}{/percent|rate|%/i.test(label)&&<small>%</small>}</strong><p className="muted small">{id?'Pilihan aktif':'Current selection'}</p>{edit&&<button className="tile-resize" aria-label={`Resize KPI ${label}`} onPointerDown={e=>gesture(e,tile,true)}>↘</button>}</section>})}
 {charts.map((chart,i)=>{const tile=tiles.find(t=>t.key===keys[i])!;return <div key={keys[i]} data-tile-key={keys[i]} className="canvas-tile" style={{gridColumn:`${tile.x+1} / span ${tile.w}`,gridRow:`${tile.y+1} / span ${tile.h}`,display:'flex'}}>{edit&&<div className="tile-tools"><button aria-label={`${id?'Di chuyển':'Move'} ${chart.title}`} onPointerDown={e=>gesture(e,tile)} onKeyDown={e=>{const offsets:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(offsets[e.key]){e.preventDefault();const [x,y]=offsets[e.key];update({...tile,x:Math.max(0,Math.min(12-tile.w,tile.x+x)),y:Math.max(0,tile.y+y)})}}}>⠿ {id?'Geser':'Move'}</button><select aria-label={`${id?'Lebar':'Width'} ${chart.title}`} value={tile.w} onChange={e=>update({...tile,w:Number(e.target.value)})}>{[3,4,5,6,7,8,9,10,11,12].map(w=><option key={w} value={w}>{Math.round(w/12*100)}%</option>)}</select><select aria-label={`${id?'Tinggi':'Height'} ${chart.title}`} value={tile.h} onChange={e=>update({...tile,h:Number(e.target.value)})}>{[...new Set([2,3,4,5,6,8,12,tile.h])].sort((a,b)=>a-b).map(h=><option key={h} value={h}>{h}</option>)}</select></div>}<DataChart chart={chart} index={i} canvas onMinimumRows={h=>minimumHeight(keys[i],h)} onCategory={chart.groupColumn===filterColumn?onCategory:undefined}/>{edit&&<button className="tile-resize" aria-label={`${id?'Ubah ukuran':'Resize'} ${chart.title}`} onPointerDown={e=>gesture(e,tile,true)}>↘</button>}</div>})}</div></div></section>
}
