'use client';
import {useRef,useState} from 'react';
import type {Chart} from '@/lib/analysis';
import {DataChart} from './data-chart';
import {placeTiles,type Tile} from '@/lib/canvas-layout';
import {useLanguage} from '@/lib/language';
export function DashboardCanvas({charts,dataset,onCategory,filterColumn,kpis={}}:{charts:Chart[];dataset:string;onCategory?:(column:string,value:string)=>void;filterColumn?:string;kpis?:Record<string,number>}){
 const {locale}=useLanguage(),id=locale==='id';const [saved,setSaved]=useState<Tile[]>([]),[page,setPage]=useState(0),[edit,setEdit]=useState(false);const root=useRef<HTMLDivElement>(null);
 const keys=charts.map((c,i)=>c.id||`${c.title}:${i}`);
 const metricTiles=Object.keys(kpis).map((label,i)=>saved.find(t=>t.key===`kpi:${label}`)||{key:`kpi:${label}`,x:(i%4)*3,y:Math.floor(i/4)*3,w:3,h:3,page:0});
 const tiles=placeTiles([...metricTiles,...charts.map((c,i)=>saved.find(t=>t.key===keys[i])||(c.position?{key:keys[i],...c.position}:null)||{key:keys[i],x:(i%2)*6,y:Math.floor(i/2)*6,w:c.width==='wide'?12:6,h:6,page:0})]);
 const pages=Math.max(1,...tiles.map(t=>t.page+1));const activePage=Math.min(page,pages-1);
 function update(tile:Tile){setSaved(placeTiles([tile,...tiles.filter(t=>t.key!==tile.key)]))}
 function gesture(e:React.PointerEvent<HTMLButtonElement>,tile:Tile,resize=false){e.preventDefault();const el=e.currentTarget;el.setPointerCapture(e.pointerId);const startX=e.clientX,startY=e.clientY,rect=root.current!.getBoundingClientRect();let next=tile;const move=(event:PointerEvent)=>{const dx=Math.round((event.clientX-startX)/rect.width*12),dy=Math.round((event.clientY-startY)/rect.height*12);next={...tile,...(resize?{w:Math.max(3,Math.min(12-tile.x,tile.w+dx)),h:Math.max(3,Math.min(12-tile.y,tile.h+dy))}:{x:Math.max(0,Math.min(12-tile.w,tile.x+dx)),y:Math.max(0,Math.min(12-tile.h,tile.y+dy))})};update(next)};const stop=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',stop);el.removeEventListener('pointercancel',stop)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',stop);el.addEventListener('pointercancel',stop)}
 return <section className="canvas-workspace"><div className="canvas-toolbar"><div><strong>{id?'Kanvas dashboard':'Dashboard canvas'}</strong><span className="muted small">{id?'Susunan AI · visualisasi tetap dipertahankan':'AI composition · existing visuals preserved'}</span></div><button onClick={()=>setEdit(v=>!v)} aria-pressed={edit}>{edit?(id?'Selesai menyusun':'Done arranging'):(id?'Atur tata letak':'Arrange layout')}</button><label>{id?'Halaman':'Page'} <select aria-label={id?'Halaman kanvas':'Canvas page'} value={activePage} onChange={e=>setPage(Number(e.target.value))}>{Array.from({length:pages},(_,i)=><option key={i} value={i}>{i+1} / {pages}</option>)}</select></label></div><div ref={root} className={'dashboard-canvas '+(edit?'editing':'')}>
 {Object.entries(kpis).map(([label,value])=>{const tile=tiles.find(t=>t.key===`kpi:${label}`)!;return <section className="canvas-tile canvas-metric metric" key={`kpi:${label}`} style={{gridColumn:`${tile.x+1} / span ${tile.w}`,gridRow:`${tile.y+1} / span ${tile.h}`,display:tile.page===activePage?'flex':'none'}}>{edit&&<div className="tile-tools"><button aria-label={`Move KPI ${label}`} onPointerDown={e=>gesture(e,tile)}>⠿ {id?'Geser':'Move'}</button><select aria-label={`Width KPI ${label}`} value={tile.w} onChange={e=>update({...tile,w:Number(e.target.value)})}>{[3,4,6,12].map(w=><option key={w} value={w}>{Math.round(w/12*100)}%</option>)}</select></div>}<span>{label}</span><strong>{new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(value)}{/percent|rate|%/i.test(label)&&<small>%</small>}</strong><p className="muted small">{id?'Pilihan aktif':'Current selection'}</p>{edit&&<button className="tile-resize" aria-label={`Resize KPI ${label}`} onPointerDown={e=>gesture(e,tile,true)}>↘</button>}</section>})}
 {charts.map((chart,i)=>{const tile=tiles.find(t=>t.key===keys[i])!;return <div key={keys[i]} className="canvas-tile" style={{gridColumn:`${tile.x+1} / span ${tile.w}`,gridRow:`${tile.y+1} / span ${tile.h}`,display:tile.page===activePage?'flex':'none'}}>{edit&&<div className="tile-tools"><button aria-label={`${id?'Di chuyển':'Move'} ${chart.title}`} onPointerDown={e=>gesture(e,tile)} onKeyDown={e=>{const offsets:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(offsets[e.key]){e.preventDefault();const [x,y]=offsets[e.key];update({...tile,x:Math.max(0,Math.min(12-tile.w,tile.x+x)),y:Math.max(0,Math.min(12-tile.h,tile.y+y))})}}}>⠿ {id?'Geser':'Move'}</button><select aria-label={`${id?'Lebar':'Width'} ${chart.title}`} value={tile.w} onChange={e=>update({...tile,w:Number(e.target.value)})}>{[3,4,6,8,12].map(w=><option key={w} value={w}>{Math.round(w/12*100)}%</option>)}</select><select aria-label={`${id?'Tinggi':'Height'} ${chart.title}`} value={tile.h} onChange={e=>update({...tile,h:Number(e.target.value)})}>{[4,6,8,12].map(h=><option key={h} value={h}>{h}</option>)}</select><select aria-label={`${id?'Halaman':'Page'} ${chart.title}`} value={tile.page} onChange={e=>update({...tile,page:Number(e.target.value)})}>{Array.from({length:pages+1},(_,p)=><option key={p} value={p}>{id?'Halaman':'Page'} {p+1}</option>)}</select></div>}<DataChart chart={chart} index={i} canvas onCategory={chart.groupColumn===filterColumn?onCategory:undefined}/>{edit&&<button className="tile-resize" aria-label={`${id?'Ubah ukuran':'Resize'} ${chart.title}`} onPointerDown={e=>gesture(e,tile,true)}>↘</button>}</div>})}</div><p className="muted small">{id?'Grafik baru ditata pada ruang tersedia. Halaman tambahan dibuat bila diperlukan.':'New charts fit into available space. Additional pages are created when needed.'}</p></section>
}
