export type Row=Record<string,unknown>;
export type Profile={rows:number;duplicates:number;columns:{name:string;type:string;missing:number}[];preview:Row[];countries:string[];months:string[]};
export type Chart={title:string;labels:string[];values:number[]};
export type Result={rows:number;kpis:Record<string,number>;charts:Chart[];definitions:string[]};
export const empty=(v:unknown)=>v==null||v==='';
export function num(v:unknown){if(empty(v))return null;let n=Number(v);return Number.isFinite(n)?n:null}
export function month(v:unknown){if(v instanceof Date&&!isNaN(v.getTime()))return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}`;if(typeof v==='number'){let d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,7)}let s=String(v??'');return /^\d{4}-\d{2}/.test(s)?s.slice(0,7):''}
export function profile(rows:Row[]):Profile{const names=Object.keys(rows[0]||{}),seen=new Set<string>();let duplicates=0;for(const r of rows){let key=JSON.stringify(names.map(c=>r[c]??null));if(seen.has(key))duplicates++;else seen.add(key)}return {rows:rows.length,duplicates,columns:names.map(name=>{let available=rows.filter(r=>!empty(r[name]));return {name,type:available.length&&available.every(r=>r[name] instanceof Date)?'date':available.length&&available.every(r=>num(r[name])!==null)?'number':'text',missing:rows.length-available.length}}),preview:rows.slice(0,8),countries:[...new Set(rows.map(r=>String(r.Country??'')).filter(Boolean))].sort(),months:[...new Set(rows.map(r=>month(r.InvoiceDate)).filter(Boolean))].sort()}}
export function dedup(rows:Row[]){let seen=new Set<string>(),keys=Object.keys(rows[0]||{});return rows.filter(r=>{let k=JSON.stringify(keys.map(c=>r[c]??null));if(seen.has(k))return false;seen.add(k);return true})}
export function selectRows(rows:Row[],filter:{country?:string;from?:string;to?:string;deduplicate?:boolean}){let d=filter.deduplicate?dedup(rows):rows;return d.filter(r=>(!filter.country||String(r.Country)===filter.country)&&(!filter.from||month(r.InvoiceDate)>=filter.from)&&(!filter.to||month(r.InvoiceDate)<=filter.to))}
export function analyze(rows:Row[]):Result{let names=Object.keys(rows[0]||{});const retail=['InvoiceNo','Quantity','UnitPrice','InvoiceDate','Country','StockCode'].every(c=>names.includes(c));let result:Result={rows:rows.length,kpis:{'Baris terpilih':rows.length,'Kolom':names.length},charts:[],definitions:[]};if(retail){let sales=0,orders=new Set<string>(),cancel=new Set<string>(),months=new Map<string,number>(),countries=new Map<string,number>(),products=new Map<string,number>();for(const r of rows){let id=String(r.InvoiceNo??''),q=num(r.Quantity),p=num(r.UnitPrice);if(id.toUpperCase().startsWith('C')){cancel.add(id);continue}if(q!==null&&p!==null&&q>0&&p>0){let v=q*p;sales+=v;orders.add(id);for(const [map,key] of [[months,month(r.InvoiceDate)],[countries,String(r.Country??'')],[products,String(r.StockCode??'')]] as [Map<string,number>,string][]){if(key)map.set(key,(map.get(key)||0)+v)}}}result.kpis={'Gross sales':sales,'Valid orders':orders.size,'Average order value':orders.size?sales/orders.size:0,'Cancellation rate (%)':orders.size+cancel.size?cancel.size/(orders.size+cancel.size)*100:0};for(const [title,map,sort] of [['Penjualan bulanan',months,false],['Top negara',countries,true],['Top produk',products,true]] as [string,Map<string,number>,boolean][]){let list=[...map.entries()].sort(sort?(a,b)=>b[1]-a[1]:(a,b)=>a[0].localeCompare(b[0]));if(sort)list=list.slice(0,10);result.charts.push({title,labels:list.map(x=>x[0]),values:list.map(x=>x[1])})}result.definitions=['Gross sales = Quantity × UnitPrice pada Quantity > 0, UnitPrice > 0 dan invoice tanpa awalan C. Mata uang mengikuti sumber data.','Valid orders = invoice unik pada penjualan valid. Cancellation rate = invoice C unik / (valid orders + invoice C unik).','Gross sales bukan nilai neto setelah retur. Baris negatif dan nilai kosong tetap dipertahankan. Monthly boundary periods may be incomplete.'];}else{for(const c of names.filter(c=>!/(id$|code$|invoice)/i.test(c)).slice(0,20)){let values=rows.map(r=>r[c]).filter(v=>!empty(v));if(!values.length)continue;if(values.every(v=>num(v)!==null)){let ns=values.map(v=>num(v)!);let min=Infinity,max=-Infinity;for(const n of ns){min=Math.min(min,n);max=Math.max(max,n)}let counts=Array(10).fill(0);for(const n of ns)counts[Math.min(9,Math.floor((n-min)/(max-min||1)*10))]++;let width=(max-min||1)/10;result.charts.push({title:'Distribusi '+c,labels:counts.map((_,i)=>`${(min+i*width).toFixed(2)}–${(min+(i+1)*width).toFixed(2)}`),values:counts})}else{let counts=new Map<string,number>();values.forEach(v=>counts.set(String(v),(counts.get(String(v))||0)+1));let top=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10);result.charts.push({title:'Frekuensi '+c,labels:top.map(x=>x[0]),values:top.map(x=>x[1])})}if(result.charts.length>=4)break}result.definitions=['Analisis eksploratif umum. Definisi KPI bisnis perlu ditentukan bersama analyst.']}return result}
export type Plan={action:'aggregate'|'clarify';question?:string;groupBy?:string;metric?:string;operation?:'sum'|'mean'|'count';title?:string};
export function executePlan(rows:Row[],p:Plan):Chart{let columns=Object.keys(rows[0]||{});if(p.action!=='aggregate'||!p.groupBy||!columns.includes(p.groupBy))throw Error('Kolom pengelompokan tidak valid.');if(!['sum','mean','count'].includes(p.operation||''))throw Error('Operasi tidak diizinkan.');if(p.operation!=='count'&&(!p.metric||!columns.includes(p.metric)||/(id$|code$|invoice)/i.test(p.metric)))throw Error('Kolom metrik tidak valid atau merupakan identifier.');let groups=new Map<string,{sum:number;count:number}>();for(const r of rows){let key=String(r[p.groupBy]??'(kosong)'),n=p.operation==='count'?1:num(r[p.metric!]);if(n===null)continue;let g=groups.get(key)||{sum:0,count:0};g.sum+=n;g.count++;groups.set(key,g);if(groups.size>10000)throw Error('Terlalu banyak kategori; pilih kolom lain.')}let list=[...groups].map(([key,v])=>[key,p.operation==='mean'?v.sum/v.count:p.operation==='count'?v.count:v.sum] as [string,number]).sort((a,b)=>b[1]-a[1]).slice(0,20);return {title:p.title||`${p.operation} ${p.metric||'baris'} per ${p.groupBy}`,labels:list.map(x=>x[0]),values:list.map(x=>x[1])}}
