import fs from 'node:fs';import ts from 'typescript';import assert from 'node:assert/strict';
const transpile=path=>ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64');
const responseModule=url(transpile('lib/ai-response.ts'));
const {relinkModels,relinkPayload,parseRelinkResponse}=await import(url(transpile('lib/relink-provider.ts').replace("'./ai-response'",JSON.stringify(responseModule))));
const approved=['deepseek-v4-flash','deepseek-v4-flash-0731','deepseek-v4-flash-vision-exp','deepseek-v4-mod','deepseek-v4-pro-0813','deepseek-v4.1-flash','deepseek-v4.1-mod','gpt-5.6','gpt-5.6-luna'];
assert.deepEqual(relinkModels({data:[...approved.map(id=>({id})),{id:'auto'},{id:'glm-5.3-flashx'},{id:'kimi-k3'},{id:'glm-5.3'},{id:'mimo-v2.6-pro'},{id:'deepseek-v4-mod'},{id:'gpt-5.6'},{id:'future-new-model'}]}).map(m=>m.id),approved.map(id=>'relink:'+id));
assert.deepEqual(relinkModels({}),[]);
assert.deepEqual(relinkModels({data:[{id:'deepseek-v4-flash',enabled:false},{id:'deepseek-v4-flash-0731',available:false},{id:'deepseek-v4-pro-0813',modalities:{output:['audio']}},{id:'gpt-5.6',enabled:true,available:true}]}),[{id:'relink:gpt-5.6',label:'gpt-5.6'}]);
const payload={systemInstruction:{parts:[{text:'Trusted rules'}]},contents:[{parts:[{text:'Untrusted summary'}]}],generationConfig:{maxOutputTokens:8192,responseJsonSchema:{type:'object',required:['ok']}}};
const converted=relinkPayload(payload,'glm-5.2');assert.equal(converted.model,'glm-5.2');assert.equal(converted.messages[0].role,'system');assert.equal(converted.messages[1].content,'Untrusted summary');assert.match(converted.messages[0].content,/required/);assert.equal(converted.response_format.type,'json_object');assert.equal(converted.max_tokens,8192);
const response=(content,finish_reason='stop')=>({choices:[{finish_reason,message:{content}}]});
assert.deepEqual(parseRelinkResponse(response('```json\n{"ok":true}\n```')),{ok:true});
assert.deepEqual(parseRelinkResponse(response([{type:'text',text:'{"ok":true}'}])),{ok:true});
for(const [r,code] of [[response('{}','length'),'AI_TRUNCATED'],[response('{}','content_filter'),'AI_BLOCKED'],[response('broken'),'AI_JSON'],[response(null),'AI_EMPTY']])assert.throws(()=>parseRelinkResponse(r),e=>e.code===code);
assert.throws(()=>parseRelinkResponse({choices:[{message:{refusal:'refused'}}]}),e=>e.code==='AI_BLOCKED');
console.log('Re:Link catalog, request conversion, JSON parsing, and failure handling passed.');
